// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import ()

type Url struct {
	Url   string `json:"url"`
	Code  string `json:"code"`
	Owner string `json:"owner"`
}

type User struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}
