// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: urls.sql

package db

import (
	"context"
)

const createUrl = `-- name: CreateUrl :one
INSERT INTO urls (
  url,
  code,
  owner
) VALUES (
  $1, $2, $3
) RETURNING url, code, owner
`

type CreateUrlParams struct {
	Url   string `json:"url"`
	Code  string `json:"code"`
	Owner string `json:"owner"`
}

func (q *Queries) CreateUrl(ctx context.Context, arg CreateUrlParams) (Url, error) {
	row := q.db.QueryRow(ctx, createUrl, arg.Url, arg.Code, arg.Owner)
	var i Url
	err := row.Scan(&i.Url, &i.Code, &i.Owner)
	return i, err
}

const getUrlByCode = `-- name: GetUrlByCode :one
SELECT url, code, owner FROM urls
WHERE code = $1
LIMIT 1
`

func (q *Queries) GetUrlByCode(ctx context.Context, code string) (Url, error) {
	row := q.db.QueryRow(ctx, getUrlByCode, code)
	var i Url
	err := row.Scan(&i.Url, &i.Code, &i.Owner)
	return i, err
}

const listUrlsByUser = `-- name: ListUrlsByUser :one
SELECT url, code, owner FROM urls
WHERE owner = $1
`

func (q *Queries) ListUrlsByUser(ctx context.Context, owner string) (Url, error) {
	row := q.db.QueryRow(ctx, listUrlsByUser, owner)
	var i Url
	err := row.Scan(&i.Url, &i.Code, &i.Owner)
	return i, err
}
